"""Public ORM model registry, organized internally by domain.

Import models from this package for backwards compatibility and to ensure Alembic
loads every table before reading ``Base.metadata``.
"""

from .assistant import ActionProposal, AgentConsent, AssistantAttempt, AssistantChunk, AssistantUserMemory
from .auth import AuditLog, PasswordResetToken, PendingRegistration, RefreshSession, User
from .base import Base
from .calendar import CalendarEvent, Reminder
from .chat import (
    Attachment,
    BlockedUser,
    CallSession,
    Conversation,
    ConversationMember,
    Message,
    MessageReaction,
    SavedMessage,
    UserSettings,
)
from .constants import (
    ACTION_PROPOSAL_SOURCE_MODES,
    ACTION_PROPOSAL_STATUSES,
    ACTION_PROPOSAL_TYPES,
    AGENT_CONSENT_POLICY_VERSION,
    AGENT_CONSENT_SCOPES,
    ASSISTANT_CHUNK_STRATEGIES,
    ASSISTANT_MEMORY_KINDS,
    ASSISTANT_OUTCOMES,
    ATTEMPT_OUTCOMES,
    CALENDAR_EVENT_SOURCES,
    CALENDAR_EVENT_STATUSES,
    DEFAULT_HONORIFIC_PROFILE,
    EMBEDDING_DIM,
    GLOSSARY_AUDIENCES,
    GLOSSARY_DOMAINS,
    GLOSSARY_ENTRY_STATUSES,
    GLOSSARY_PROPOSAL_STATUSES,
    HONORIFIC_PROFILES,
    MESSAGE_LIFECYCLE_CHECK,
    MESSAGE_TYPES,
    MESSAGE_VISIBILITIES,
    TRANSCRIPTION_STATUSES,
    TRANSLATION_TONES,
)
from .delivery import PushSubscription, WebhookDelivery, WebhookEndpoint
from .translation import (
    ConversationProfile,
    CorrectionLog,
    Feedback,
    GlossaryEntry,
    GlossaryProposal,
    GlossaryProposalCitation,
    MessageEmbedding,
    ParticipantProfile,
    TranslationAttempt,
    TranslationEdit,
    TranslationResult,
)

__all__ = [
    "Base",
    "EMBEDDING_DIM",
    "HONORIFIC_PROFILES",
    "DEFAULT_HONORIFIC_PROFILE",
    "GLOSSARY_AUDIENCES",
    "GLOSSARY_DOMAINS",
    "TRANSLATION_TONES",
    "MESSAGE_TYPES",
    "TRANSCRIPTION_STATUSES",
    "MESSAGE_LIFECYCLE_CHECK",
    "GLOSSARY_ENTRY_STATUSES",
    "GLOSSARY_PROPOSAL_STATUSES",
    "AGENT_CONSENT_SCOPES",
    "MESSAGE_VISIBILITIES",
    "CALENDAR_EVENT_SOURCES",
    "CALENDAR_EVENT_STATUSES",
    "AGENT_CONSENT_POLICY_VERSION",
    "ATTEMPT_OUTCOMES",
    "ACTION_PROPOSAL_TYPES",
    "ACTION_PROPOSAL_STATUSES",
    "ACTION_PROPOSAL_SOURCE_MODES",
    "ASSISTANT_CHUNK_STRATEGIES",
    "ASSISTANT_MEMORY_KINDS",
    "ASSISTANT_OUTCOMES",
    "User",
    "AuditLog",
    "RefreshSession",
    "PasswordResetToken",
    "PendingRegistration",
    "Conversation",
    "ConversationMember",
    "UserSettings",
    "BlockedUser",
    "CallSession",
    "Message",
    "SavedMessage",
    "MessageReaction",
    "Attachment",
    "TranslationResult",
    "Feedback",
    "TranslationEdit",
    "TranslationAttempt",
    "ConversationProfile",
    "ParticipantProfile",
    "GlossaryEntry",
    "GlossaryProposal",
    "GlossaryProposalCitation",
    "CorrectionLog",
    "MessageEmbedding",
    "AgentConsent",
    "ActionProposal",
    "AssistantChunk",
    "AssistantUserMemory",
    "AssistantAttempt",
    "CalendarEvent",
    "Reminder",
    "WebhookEndpoint",
    "WebhookDelivery",
    "PushSubscription",
]
