import type { LanguageCode } from "../types";

const interactionKeys = ["Messages are translated in real-time. Speak your native language freely.","Replying to","Document or File","Message","Forwarded","Forward","Translate again","Save message","Delete","Search contacts...","Search study groups...","Search people to add...","Select Group Members","Group Details","Create Group","Group icon","Group Name","Description (Optional)","What is this group for?"];
const interactionValues: Record<LanguageCode, string[]> = {
  en: ["Messages are translated automatically. Write in your preferred language.","Replying to","Document or file","Message","Forwarded","Forward","Translate again","Save message","Delete","Search contacts...","Search groups...","Search people...","Add members","Group details","Create group","Group icon","Group name","Description (optional)","What is this group for?"],
  vi: ["Tin nhắn được dịch theo thời gian thực. Hãy thoải mái dùng ngôn ngữ của bạn.","Đang trả lời","Tài liệu hoặc tệp","Nhắn tin","Đã chuyển tiếp","Chuyển tiếp","Dịch lại","Lưu tin nhắn","Xóa","Tìm kiếm liên hệ...","Tìm kiếm nhóm...","Tìm người để thêm...","Chọn thành viên nhóm","Chi tiết nhóm","Tạo nhóm","Biểu tượng nhóm","Tên nhóm","Mô tả (Không bắt buộc)","Nhóm này dùng để làm gì?"],
  ja: ["メッセージはリアルタイムで翻訳されます。母国語で自由に話してください。","返信先","文書またはファイル","メッセージ","転送済み","転送","再翻訳","メッセージを保存","削除","連絡先を検索...","グループを検索...","追加する人を検索...","グループメンバーを選択","グループの詳細","グループを作成","グループアイコン","グループ名","説明（任意）","このグループの目的は？"],
  ko: ["메시지는 실시간으로 번역됩니다. 모국어로 자유롭게 대화하세요.","답장 대상","문서 또는 파일","메시지","전달됨","전달","다시 번역","메시지 저장","삭제","연락처 검색...","그룹 검색...","추가할 사람 검색...","그룹 멤버 선택","그룹 세부정보","그룹 만들기","그룹 아이콘","그룹 이름","설명(선택 사항)","이 그룹의 목적은 무엇인가요?"],
  zh: ["消息会实时翻译。请放心使用您的母语交流。","回复","文档或文件","消息","已转发","转发","重新翻译","保存消息","删除","搜索联系人...","搜索群组...","搜索要添加的人...","选择群组成员","群组详情","创建群组","群组图标","群组名称","描述（可选）","这个群组用于什么？"],
  es: ["Los mensajes se traducen en tiempo real. Habla libremente en tu idioma nativo.","Respondiendo a","Documento o archivo","Mensaje","Reenviado","Reenviar","Traducir de nuevo","Guardar mensaje","Eliminar","Buscar contactos...","Buscar grupos...","Buscar personas para añadir...","Seleccionar miembros del grupo","Detalles del grupo","Crear grupo","Icono del grupo","Nombre del grupo","Descripción (opcional)","¿Para qué es este grupo?"],
  fr: ["Les messages sont traduits en temps réel. Parlez librement dans votre langue maternelle.","Réponse à","Document ou fichier","Message","Transféré","Transférer","Retraduire","Enregistrer le message","Supprimer","Rechercher des contacts...","Rechercher des groupes...","Rechercher des personnes à ajouter...","Sélectionner les membres","Détails du groupe","Créer le groupe","Icône du groupe","Nom du groupe","Description (facultative)","À quoi sert ce groupe ?"],
  de: ["Nachrichten werden in Echtzeit übersetzt. Schreiben Sie frei in Ihrer Muttersprache.","Antwort an","Dokument oder Datei","Nachricht","Weitergeleitet","Weiterleiten","Erneut übersetzen","Nachricht speichern","Löschen","Kontakte suchen...","Gruppen suchen...","Personen zum Hinzufügen suchen...","Gruppenmitglieder auswählen","Gruppendetails","Gruppe erstellen","Gruppensymbol","Gruppenname","Beschreibung (optional)","Wofür ist diese Gruppe gedacht?"],
  th: ["ข้อความได้รับการแปลแบบเรียลไทม์ ใช้ภาษาแม่ของคุณได้อย่างอิสระ","กำลังตอบกลับ","เอกสารหรือไฟล์","ข้อความ","ส่งต่อแล้ว","ส่งต่อ","แปลอีกครั้ง","บันทึกข้อความ","ลบ","ค้นหาผู้ติดต่อ...","ค้นหากลุ่ม...","ค้นหาคนที่จะเพิ่ม...","เลือกสมาชิกกลุ่ม","รายละเอียดกลุ่ม","สร้างกลุ่ม","ไอคอนกลุ่ม","ชื่อกลุ่ม","คำอธิบาย (ไม่บังคับ)","กลุ่มนี้มีไว้เพื่ออะไร?"],
  id: ["Pesan diterjemahkan secara real-time. Gunakan bahasa ibu Anda dengan bebas.","Membalas","Dokumen atau file","Pesan","Diteruskan","Teruskan","Terjemahkan lagi","Simpan pesan","Hapus","Cari kontak...","Cari grup...","Cari orang untuk ditambahkan...","Pilih anggota grup","Detail grup","Buat grup","Ikon grup","Nama grup","Deskripsi (opsional)","Untuk apa grup ini?"],
  pt: ["As mensagens são traduzidas em tempo real. Use seu idioma livremente.","Respondendo a","Documento ou arquivo","Mensagem","Encaminhada","Encaminhar","Traduzir novamente","Salvar mensagem","Excluir","Pesquisar contatos...","Pesquisar grupos...","Pesquisar pessoas para adicionar...","Selecionar membros do grupo","Detalhes do grupo","Criar grupo","Ícone do grupo","Nome do grupo","Descrição (opcional)","Para que serve este grupo?"],
  ru: ["Сообщения переводятся в реальном времени. Пишите на родном языке.","Ответ на","Документ или файл","Сообщение","Переслано","Переслать","Перевести снова","Сохранить сообщение","Удалить","Поиск контактов...","Поиск групп...","Поиск людей для добавления...","Выбрать участников группы","Сведения о группе","Создать группу","Значок группы","Название группы","Описание (необязательно)","Для чего эта группа?"],
  ar: ["تُترجم الرسائل في الوقت الفعلي. استخدم لغتك بحرية.","رد على","مستند أو ملف","رسالة","تمت إعادة التوجيه","إعادة توجيه","ترجمة مرة أخرى","حفظ الرسالة","حذف","ابحث في جهات الاتصال...","ابحث في المجموعات...","ابحث عن أشخاص لإضافتهم...","اختر أعضاء المجموعة","تفاصيل المجموعة","إنشاء مجموعة","أيقونة المجموعة","اسم المجموعة","الوصف (اختياري)","لأي غرض هذه المجموعة؟"],
  hi: ["संदेश रीयल-टाइम में अनुवादित होते हैं। अपनी भाषा का बेझिझक उपयोग करें।","को उत्तर","दस्तावेज़ या फ़ाइल","संदेश","अग्रेषित","अग्रेषित करें","फिर से अनुवाद करें","संदेश सहेजें","हटाएँ","संपर्क खोजें...","समूह खोजें...","जोड़ने के लिए लोगों को खोजें...","समूह सदस्य चुनें","समूह विवरण","समूह बनाएँ","समूह आइकन","समूह का नाम","विवरण (वैकल्पिक)","यह समूह किस लिए है?"],
};
const interactionExtras: Record<LanguageCode, Record<string, string>> = {
  en: {"Show original":"Show original","Hide original":"Hide original","Show translation":"Show translation","Hide translation":"Hide translation","Shared files":"Shared files","No files shared yet":"No files shared yet","Download file":"Download file","Group translations notice":"Incoming messages are automatically translated into each member's preferred language.","Only you can see this":"Only you can see this"},
  vi: {"Show original":"Hiện bản gốc","Hide original":"Ẩn bản gốc","Show translation":"Hiện bản dịch","Hide translation":"Ẩn bản dịch","Shared files":"Tệp đã chia sẻ","No files shared yet":"Chưa có tệp nào được chia sẻ","Download file":"Tải tệp xuống","Group translations notice":"Tin nhắn gửi đến được tự động dịch sang ngôn ngữ ưu tiên của từng thành viên.","Only you can see this":"Chỉ bạn nhìn thấy"},
  ja: {"Show original":"原文を表示","Hide original":"原文を非表示","Show translation":"翻訳を表示","Hide translation":"翻訳を非表示","Shared files":"共有ファイル","No files shared yet":"共有されたファイルはありません","Download file":"ファイルをダウンロード","Group translations notice":"受信メッセージは各メンバーの優先言語に自動翻訳されます。","Only you can see this":"あなただけに表示されています"},
  ko: {"Show original":"원문 표시","Hide original":"원문 숨기기","Show translation":"번역 표시","Hide translation":"번역 숨기기","Shared files":"공유 파일","No files shared yet":"공유된 파일이 없습니다","Download file":"파일 다운로드","Group translations notice":"수신 메시지는 각 구성원의 선호 언어로 자동 번역됩니다.","Only you can see this":"나만 볼 수 있습니다"},
  zh: {"Show original":"显示原文","Hide original":"隐藏原文","Show translation":"显示译文","Hide translation":"隐藏译文","Shared files":"共享文件","No files shared yet":"暂无共享文件","Download file":"下载文件","Group translations notice":"收到的消息会自动翻译为每位成员的首选语言。","Only you can see this":"仅你可见"},
  es: {"Show original":"Mostrar original","Hide original":"Ocultar original","Show translation":"Mostrar traducción","Hide translation":"Ocultar traducción","Shared files":"Archivos compartidos","No files shared yet":"Aún no se han compartido archivos","Download file":"Descargar archivo","Group translations notice":"Los mensajes entrantes se traducen automáticamente al idioma preferido de cada miembro.","Only you can see this":"Solo tú puedes verlo"},
  fr: {"Show original":"Afficher l’original","Hide original":"Masquer l’original","Show translation":"Afficher la traduction","Hide translation":"Masquer la traduction","Shared files":"Fichiers partagés","No files shared yet":"Aucun fichier partagé","Download file":"Télécharger le fichier","Group translations notice":"Les messages reçus sont automatiquement traduits dans la langue préférée de chaque membre.","Only you can see this":"Vous seul pouvez le voir"},
  de: {"Show original":"Original anzeigen","Hide original":"Original ausblenden","Show translation":"Übersetzung anzeigen","Hide translation":"Übersetzung ausblenden","Shared files":"Geteilte Dateien","No files shared yet":"Noch keine Dateien geteilt","Download file":"Datei herunterladen","Group translations notice":"Eingehende Nachrichten werden automatisch in die bevorzugte Sprache jedes Mitglieds übersetzt.","Only you can see this":"Nur für dich sichtbar"},
  th: {"Show original":"แสดงต้นฉบับ","Hide original":"ซ่อนต้นฉบับ","Show translation":"แสดงคำแปล","Hide translation":"ซ่อนคำแปล","Shared files":"ไฟล์ที่แชร์","No files shared yet":"ยังไม่มีไฟล์ที่แชร์","Download file":"ดาวน์โหลดไฟล์","Group translations notice":"ข้อความที่ได้รับจะแปลเป็นภาษาที่ต้องการของสมาชิกแต่ละคนโดยอัตโนมัติ","Only you can see this":"มีเพียงคุณที่เห็นข้อความนี้"},
  id: {"Show original":"Tampilkan asli","Hide original":"Sembunyikan asli","Show translation":"Tampilkan terjemahan","Hide translation":"Sembunyikan terjemahan","Shared files":"File yang dibagikan","No files shared yet":"Belum ada file yang dibagikan","Download file":"Unduh file","Group translations notice":"Pesan masuk otomatis diterjemahkan ke bahasa pilihan setiap anggota.","Only you can see this":"Hanya kamu yang bisa melihat ini"},
  pt: {"Show original":"Mostrar original","Hide original":"Ocultar original","Show translation":"Mostrar tradução","Hide translation":"Ocultar tradução","Shared files":"Arquivos compartilhados","No files shared yet":"Nenhum arquivo compartilhado ainda","Download file":"Baixar arquivo","Group translations notice":"As mensagens recebidas são traduzidas automaticamente para o idioma preferido de cada membro.","Only you can see this":"Só você pode ver isto"},
  ru: {"Show original":"Показать оригинал","Hide original":"Скрыть оригинал","Show translation":"Показать перевод","Hide translation":"Скрыть перевод","Shared files":"Общие файлы","No files shared yet":"Общих файлов пока нет","Download file":"Скачать файл","Group translations notice":"Входящие сообщения автоматически переводятся на язык каждого участника.","Only you can see this":"Это видите только вы"},
  ar: {"Show original":"إظهار الأصل","Hide original":"إخفاء الأصل","Show translation":"إظهار الترجمة","Hide translation":"إخفاء الترجمة","Shared files":"الملفات المشتركة","No files shared yet":"لا توجد ملفات مشتركة بعد","Download file":"تنزيل الملف","Group translations notice":"تُترجم الرسائل الواردة تلقائيًا إلى اللغة المفضلة لكل عضو.","Only you can see this":"أنت وحدك من يرى هذا"},
  hi: {"Show original":"मूल दिखाएँ","Hide original":"मूल छिपाएँ","Show translation":"अनुवाद दिखाएँ","Hide translation":"अनुवाद छिपाएँ","Shared files":"साझा की गई फ़ाइलें","No files shared yet":"अभी कोई फ़ाइल साझा नहीं की गई","Download file":"फ़ाइल डाउनलोड करें","Group translations notice":"आने वाले संदेश स्वचालित रूप से प्रत्येक सदस्य की पसंदीदा भाषा में अनुवादित होते हैं।","Only you can see this":"इसे केवल आप देख सकते हैं"},
};

const voiceMessageCopy: Record<LanguageCode, Record<string, string>> = {
  en: {"Voice message":"Voice message","Record voice message":"Record voice message","Recording…":"Recording…","Requesting microphone permission…":"Requesting microphone permission…","Stopping recording…":"Stopping recording…","Uploading voice message…":"Uploading voice message…","Sending voice message…":"Sending voice message…","Transcribing…":"Transcribing…","Transcription unavailable":"Transcription unavailable","Microphone permission denied":"Microphone permission denied","Microphone unavailable":"Microphone unavailable","Unsupported recording format":"Unsupported recording format","Recording failed":"Recording failed","Empty recording":"Empty recording","Cancel recording":"Cancel recording","Send voice message":"Send voice message","Could not upload voice message":"Could not upload voice message","Could not send voice message":"Could not send voice message","Dismiss error":"Dismiss error"},
  vi: {"Voice message":"Tin nhắn thoại","Record voice message":"Ghi âm tin nhắn thoại","Recording…":"Đang ghi âm…","Requesting microphone permission…":"Đang xin quyền truy cập micrô…","Stopping recording…":"Đang dừng ghi âm…","Uploading voice message…":"Đang tải tin nhắn thoại lên…","Sending voice message…":"Đang gửi tin nhắn thoại…","Transcribing…":"Đang chuyển giọng nói thành văn bản…","Transcription unavailable":"Không thể chuyển giọng nói thành văn bản","Microphone permission denied":"Quyền truy cập micrô bị từ chối","Microphone unavailable":"Micrô không khả dụng","Unsupported recording format":"Định dạng ghi âm không được hỗ trợ","Recording failed":"Ghi âm thất bại","Empty recording":"Bản ghi âm trống","Cancel recording":"Hủy ghi âm","Send voice message":"Gửi tin nhắn thoại","Could not upload voice message":"Không thể tải tin nhắn thoại lên","Could not send voice message":"Không thể gửi tin nhắn thoại","Dismiss error":"Đóng lỗi"},
  ja: {"Voice message":"音声メッセージ","Record voice message":"音声メッセージを録音","Recording…":"録音中…","Requesting microphone permission…":"マイクの許可を確認中…","Stopping recording…":"録音を停止中…","Uploading voice message…":"音声メッセージをアップロード中…","Sending voice message…":"音声メッセージを送信中…","Transcribing…":"文字起こし中…","Transcription unavailable":"文字起こしを利用できません","Microphone permission denied":"マイクの許可が拒否されました","Microphone unavailable":"マイクを利用できません","Unsupported recording format":"録音形式がサポートされていません","Recording failed":"録音に失敗しました","Empty recording":"録音が空です","Cancel recording":"録音をキャンセル","Send voice message":"音声メッセージを送信","Could not upload voice message":"音声メッセージをアップロードできませんでした","Could not send voice message":"音声メッセージを送信できませんでした","Dismiss error":"エラーを閉じる"},
  ko: {"Voice message":"음성 메시지","Record voice message":"음성 메시지 녹음","Recording…":"녹음 중…","Requesting microphone permission…":"마이크 권한 요청 중…","Stopping recording…":"녹음 중지 중…","Uploading voice message…":"음성 메시지 업로드 중…","Sending voice message…":"음성 메시지 전송 중…","Transcribing…":"음성을 텍스트로 변환 중…","Transcription unavailable":"음성 변환을 사용할 수 없습니다","Microphone permission denied":"마이크 권한이 거부되었습니다","Microphone unavailable":"마이크를 사용할 수 없습니다","Unsupported recording format":"지원되지 않는 녹음 형식입니다","Recording failed":"녹음에 실패했습니다","Empty recording":"녹음 내용이 없습니다","Cancel recording":"녹음 취소","Send voice message":"음성 메시지 보내기","Could not upload voice message":"음성 메시지를 업로드할 수 없습니다","Could not send voice message":"음성 메시지를 보낼 수 없습니다","Dismiss error":"오류 닫기"},
  zh: {"Voice message":"语音消息","Record voice message":"录制语音消息","Recording…":"正在录音…","Requesting microphone permission…":"正在请求麦克风权限…","Stopping recording…":"正在停止录音…","Uploading voice message…":"正在上传语音消息…","Sending voice message…":"正在发送语音消息…","Transcribing…":"正在转写…","Transcription unavailable":"无法提供转写文本","Microphone permission denied":"麦克风权限被拒绝","Microphone unavailable":"麦克风不可用","Unsupported recording format":"不支持此录音格式","Recording failed":"录音失败","Empty recording":"录音为空","Cancel recording":"取消录音","Send voice message":"发送语音消息","Could not upload voice message":"无法上传语音消息","Could not send voice message":"无法发送语音消息","Dismiss error":"关闭错误"},
  es: {"Voice message":"Mensaje de voz","Record voice message":"Grabar mensaje de voz","Recording…":"Grabando…","Requesting microphone permission…":"Solicitando permiso para el micrófono…","Stopping recording…":"Deteniendo la grabación…","Uploading voice message…":"Subiendo mensaje de voz…","Sending voice message…":"Enviando mensaje de voz…","Transcribing…":"Transcribiendo…","Transcription unavailable":"Transcripción no disponible","Microphone permission denied":"Permiso del micrófono denegado","Microphone unavailable":"Micrófono no disponible","Unsupported recording format":"Formato de grabación no compatible","Recording failed":"Error al grabar","Empty recording":"La grabación está vacía","Cancel recording":"Cancelar grabación","Send voice message":"Enviar mensaje de voz","Could not upload voice message":"No se pudo subir el mensaje de voz","Could not send voice message":"No se pudo enviar el mensaje de voz","Dismiss error":"Cerrar error"},
  fr: {"Voice message":"Message vocal","Record voice message":"Enregistrer un message vocal","Recording…":"Enregistrement…","Requesting microphone permission…":"Demande d’autorisation du micro…","Stopping recording…":"Arrêt de l’enregistrement…","Uploading voice message…":"Téléversement du message vocal…","Sending voice message…":"Envoi du message vocal…","Transcribing…":"Transcription…","Transcription unavailable":"Transcription indisponible","Microphone permission denied":"Autorisation du micro refusée","Microphone unavailable":"Micro indisponible","Unsupported recording format":"Format d’enregistrement non pris en charge","Recording failed":"Échec de l’enregistrement","Empty recording":"L’enregistrement est vide","Cancel recording":"Annuler l’enregistrement","Send voice message":"Envoyer le message vocal","Could not upload voice message":"Impossible de téléverser le message vocal","Could not send voice message":"Impossible d’envoyer le message vocal","Dismiss error":"Fermer l’erreur"},
  de: {"Voice message":"Sprachnachricht","Record voice message":"Sprachnachricht aufnehmen","Recording…":"Aufnahme läuft…","Requesting microphone permission…":"Mikrofonberechtigung wird angefragt…","Stopping recording…":"Aufnahme wird beendet…","Uploading voice message…":"Sprachnachricht wird hochgeladen…","Sending voice message…":"Sprachnachricht wird gesendet…","Transcribing…":"Transkription läuft…","Transcription unavailable":"Transkription nicht verfügbar","Microphone permission denied":"Mikrofonberechtigung verweigert","Microphone unavailable":"Mikrofon nicht verfügbar","Unsupported recording format":"Aufnahmeformat nicht unterstützt","Recording failed":"Aufnahme fehlgeschlagen","Empty recording":"Aufnahme ist leer","Cancel recording":"Aufnahme abbrechen","Send voice message":"Sprachnachricht senden","Could not upload voice message":"Sprachnachricht konnte nicht hochgeladen werden","Could not send voice message":"Sprachnachricht konnte nicht gesendet werden","Dismiss error":"Fehler schließen"},
  th: {"Voice message":"ข้อความเสียง","Record voice message":"บันทึกข้อความเสียง","Recording…":"กำลังบันทึก…","Requesting microphone permission…":"กำลังขอสิทธิ์ไมโครโฟน…","Stopping recording…":"กำลังหยุดบันทึก…","Uploading voice message…":"กำลังอัปโหลดข้อความเสียง…","Sending voice message…":"กำลังส่งข้อความเสียง…","Transcribing…":"กำลังถอดเสียง…","Transcription unavailable":"ไม่มีข้อความถอดเสียง","Microphone permission denied":"สิทธิ์ไมโครโฟนถูกปฏิเสธ","Microphone unavailable":"ไม่สามารถใช้ไมโครโฟนได้","Unsupported recording format":"ไม่รองรับรูปแบบการบันทึกนี้","Recording failed":"บันทึกเสียงไม่สำเร็จ","Empty recording":"ไม่มีเสียงที่บันทึก","Cancel recording":"ยกเลิกการบันทึก","Send voice message":"ส่งข้อความเสียง","Could not upload voice message":"ไม่สามารถอัปโหลดข้อความเสียงได้","Could not send voice message":"ไม่สามารถส่งข้อความเสียงได้","Dismiss error":"ปิดข้อผิดพลาด"},
  id: {"Voice message":"Pesan suara","Record voice message":"Rekam pesan suara","Recording…":"Merekam…","Requesting microphone permission…":"Meminta izin mikrofon…","Stopping recording…":"Menghentikan rekaman…","Uploading voice message…":"Mengunggah pesan suara…","Sending voice message…":"Mengirim pesan suara…","Transcribing…":"Mentranskripsikan…","Transcription unavailable":"Transkripsi tidak tersedia","Microphone permission denied":"Izin mikrofon ditolak","Microphone unavailable":"Mikrofon tidak tersedia","Unsupported recording format":"Format rekaman tidak didukung","Recording failed":"Perekaman gagal","Empty recording":"Rekaman kosong","Cancel recording":"Batalkan rekaman","Send voice message":"Kirim pesan suara","Could not upload voice message":"Pesan suara tidak dapat diunggah","Could not send voice message":"Pesan suara tidak dapat dikirim","Dismiss error":"Tutup kesalahan"},
  pt: {"Voice message":"Mensagem de voz","Record voice message":"Gravar mensagem de voz","Recording…":"Gravando…","Requesting microphone permission…":"Solicitando permissão do microfone…","Stopping recording…":"Parando a gravação…","Uploading voice message…":"Enviando áudio…","Sending voice message…":"Enviando mensagem de voz…","Transcribing…":"Transcrevendo…","Transcription unavailable":"Transcrição indisponível","Microphone permission denied":"Permissão do microfone negada","Microphone unavailable":"Microfone indisponível","Unsupported recording format":"Formato de gravação não compatível","Recording failed":"Falha na gravação","Empty recording":"A gravação está vazia","Cancel recording":"Cancelar gravação","Send voice message":"Enviar mensagem de voz","Could not upload voice message":"Não foi possível carregar a mensagem de voz","Could not send voice message":"Não foi possível enviar a mensagem de voz","Dismiss error":"Fechar erro"},
  ru: {"Voice message":"Голосовое сообщение","Record voice message":"Записать голосовое сообщение","Recording…":"Идёт запись…","Requesting microphone permission…":"Запрашивается доступ к микрофону…","Stopping recording…":"Запись останавливается…","Uploading voice message…":"Голосовое сообщение загружается…","Sending voice message…":"Голосовое сообщение отправляется…","Transcribing…":"Идёт расшифровка…","Transcription unavailable":"Расшифровка недоступна","Microphone permission denied":"Доступ к микрофону запрещён","Microphone unavailable":"Микрофон недоступен","Unsupported recording format":"Формат записи не поддерживается","Recording failed":"Не удалось записать","Empty recording":"Запись пуста","Cancel recording":"Отменить запись","Send voice message":"Отправить голосовое сообщение","Could not upload voice message":"Не удалось загрузить голосовое сообщение","Could not send voice message":"Не удалось отправить голосовое сообщение","Dismiss error":"Закрыть ошибку"},
  ar: {"Voice message":"رسالة صوتية","Record voice message":"تسجيل رسالة صوتية","Recording…":"جارٍ التسجيل…","Requesting microphone permission…":"جارٍ طلب إذن الميكروفون…","Stopping recording…":"جارٍ إيقاف التسجيل…","Uploading voice message…":"جارٍ رفع الرسالة الصوتية…","Sending voice message…":"جارٍ إرسال الرسالة الصوتية…","Transcribing…":"جارٍ النسخ…","Transcription unavailable":"النسخ غير متاح","Microphone permission denied":"تم رفض إذن الميكروفون","Microphone unavailable":"الميكروفون غير متاح","Unsupported recording format":"تنسيق التسجيل غير مدعوم","Recording failed":"فشل التسجيل","Empty recording":"التسجيل فارغ","Cancel recording":"إلغاء التسجيل","Send voice message":"إرسال رسالة صوتية","Could not upload voice message":"تعذر رفع الرسالة الصوتية","Could not send voice message":"تعذر إرسال الرسالة الصوتية","Dismiss error":"إغلاق الخطأ"},
  hi: {"Voice message":"वॉइस संदेश","Record voice message":"वॉइस संदेश रिकॉर्ड करें","Recording…":"रिकॉर्ड हो रहा है…","Requesting microphone permission…":"माइक्रोफ़ोन की अनुमति माँगी जा रही है…","Stopping recording…":"रिकॉर्डिंग रोकी जा रही है…","Uploading voice message…":"वॉइस संदेश अपलोड हो रहा है…","Sending voice message…":"वॉइस संदेश भेजा जा रहा है…","Transcribing…":"लिप्यंतरण हो रहा है…","Transcription unavailable":"लिप्यंतरण उपलब्ध नहीं है","Microphone permission denied":"माइक्रोफ़ोन की अनुमति अस्वीकार की गई","Microphone unavailable":"माइक्रोफ़ोन उपलब्ध नहीं है","Unsupported recording format":"रिकॉर्डिंग प्रारूप समर्थित नहीं है","Recording failed":"रिकॉर्डिंग विफल रही","Empty recording":"रिकॉर्डिंग खाली है","Cancel recording":"रिकॉर्डिंग रद्द करें","Send voice message":"वॉइस संदेश भेजें","Could not upload voice message":"वॉइस संदेश अपलोड नहीं हो सका","Could not send voice message":"वॉइस संदेश भेजा नहीं जा सका","Dismiss error":"त्रुटि बंद करें"},
};

const voiceRetryCopy: Record<LanguageCode, Record<string, string>> = {
  en: {"Retry transcription":"Retry transcription","Retrying transcription…":"Retrying transcription…","Could not retry transcription":"Could not retry transcription"},
  vi: {"Retry transcription":"Thử chuyển lời lại","Retrying transcription…":"Đang thử chuyển lời lại…","Could not retry transcription":"Không thể thử chuyển lời lại"},
  ja: {"Retry transcription":"文字起こしを再試行","Retrying transcription…":"文字起こしを再試行中…","Could not retry transcription":"文字起こしを再試行できませんでした"},
  ko: {"Retry transcription":"음성 변환 다시 시도","Retrying transcription…":"음성 변환 다시 시도 중…","Could not retry transcription":"음성 변환을 다시 시도할 수 없습니다"},
  zh: {"Retry transcription":"重试转写","Retrying transcription…":"正在重试转写…","Could not retry transcription":"无法重试转写"},
  es: {"Retry transcription":"Reintentar transcripción","Retrying transcription…":"Reintentando la transcripción…","Could not retry transcription":"No se pudo reintentar la transcripción"},
  fr: {"Retry transcription":"Réessayer la transcription","Retrying transcription…":"Nouvelle tentative de transcription…","Could not retry transcription":"Impossible de relancer la transcription"},
  de: {"Retry transcription":"Transkription erneut versuchen","Retrying transcription…":"Transkription wird erneut versucht…","Could not retry transcription":"Transkription konnte nicht erneut versucht werden"},
  th: {"Retry transcription":"ลองถอดเสียงอีกครั้ง","Retrying transcription…":"กำลังลองถอดเสียงอีกครั้ง…","Could not retry transcription":"ไม่สามารถลองถอดเสียงอีกครั้งได้"},
  id: {"Retry transcription":"Coba transkripsi lagi","Retrying transcription…":"Mencoba transkripsi lagi…","Could not retry transcription":"Tidak dapat mencoba transkripsi lagi"},
  pt: {"Retry transcription":"Tentar transcrição novamente","Retrying transcription…":"Tentando transcrever novamente…","Could not retry transcription":"Não foi possível tentar a transcrição novamente"},
  ru: {"Retry transcription":"Повторить расшифровку","Retrying transcription…":"Повторная расшифровка…","Could not retry transcription":"Не удалось повторить расшифровку"},
  ar: {"Retry transcription":"إعادة محاولة النسخ","Retrying transcription…":"جارٍ إعادة محاولة النسخ…","Could not retry transcription":"تعذرت إعادة محاولة النسخ"},
  hi: {"Retry transcription":"लिप्यंतरण फिर से आज़माएँ","Retrying transcription…":"लिप्यंतरण फिर से आज़माया जा रहा है…","Could not retry transcription":"लिप्यंतरण फिर से नहीं किया जा सका"},
};
export const interactionText = (language: LanguageCode, value: string) => {
  const index = interactionKeys.indexOf(value);
  return index < 0
    ? (interactionExtras[language][value] || voiceMessageCopy[language][value] || voiceRetryCopy[language][value] || value)
    : interactionValues[language][index];
};
