import type { LanguageCode } from "../types";

const phrases: Partial<Record<LanguageCode, Record<string, string>>> = {
  en: { Contacts: "Contacts", Groups: "Groups", "Search contacts...": "Search contacts...", "Search study groups...": "Search groups...", "multilingual members": "members", "Auto Live Translation Active": "Live translation is on", "Contact Details": "Contact info", "Group Information": "Group info", "Native Language": "Preferred language", "Global Members": "Members", "Mute Notifications": "Mute notifications", Muted: "Muted", Off: "Off", "Pin Conversation": "Pin chat", Pinned: "Pinned", No: "No", Members: "Members", Member: "Member", "Leave Group": "Leave group", "Block Contact": "Block contact", "My Profile": "Profile", Appearance: "Appearance", "Language & Settings": "Language & translation", "Log out": "Log out", "Logging out…": "Logging out…", Light: "Light", Dark: "Dark", "Last seen recently": "Last seen recently", Online: "Online", "New Conversation": "New chat", "Create a New Group": "Create group", "Suggested Contacts": "Suggested contacts", "Forward message": "Forward message", "No other conversation to forward to.": "No other chats available.", "Start a new chat": "Start a new chat" },
  vi: { Contacts: "Liên hệ", Groups: "Nhóm", "Search contacts...": "Tìm kiếm liên hệ...", "Search study groups...": "Tìm kiếm nhóm...", "multilingual members": "thành viên đa ngôn ngữ", "Auto Live Translation Active": "Đang bật dịch trực tiếp tự động", "Contact Details": "Chi tiết liên hệ", "Group Information": "Thông tin nhóm", "Native Language": "Ngôn ngữ mẹ đẻ", "Global Members": "Thành viên quốc tế", "Mute Notifications": "Tắt thông báo", Muted: "Đã tắt", Off: "Tắt", "Pin Conversation": "Ghim cuộc trò chuyện", Pinned: "Đã ghim", No: "Không", Members: "Thành viên", Member: "Thành viên", "Leave Group": "Rời nhóm", "Block Contact": "Chặn liên hệ", "My Profile": "Hồ sơ của tôi", Appearance: "Giao diện", "Language & Settings": "Ngôn ngữ & Cài đặt", "Log out": "Đăng xuất", "Logging out…": "Đang đăng xuất…", Light: "Sáng", Dark: "Tối", "Last seen recently": "Hoạt động gần đây", Online: "Đang hoạt động", "New Conversation": "Cuộc trò chuyện mới", "Create a New Group": "Tạo nhóm mới", "Suggested Contacts": "Liên hệ đề xuất", "Forward message": "Chuyển tiếp tin nhắn", "No other conversation to forward to.": "Không có cuộc trò chuyện khác để chuyển tiếp.", "Start a new chat": "Bắt đầu cuộc trò chuyện mới", Event: "Sự kiện", Events: "Sự kiện", Task: "Việc cần làm", Tasks: "Việc cần làm", Type: "Loại", "Task inbox": "Hộp nhiệm vụ", "Review proposals from your assistant": "Theo dõi và duyệt các đề xuất từ trợ lý", "Awaiting review": "Cần duyệt", Processed: "Đã xử lý", "Hello! How can I help?": "Chào bạn! Tôi có thể hỗ trợ gì?", Now: "Bây giờ", "Create reminder": "Tạo nhắc hẹn", "Find appointments": "Tìm lịch hẹn", "Awaiting approval": "Chờ duyệt", Approved: "Đã duyệt", Rejected: "Đã từ chối", Approve: "Duyệt", Reject: "Từ chối", Source: "Nguồn", "Created at": "Thời gian tạo", "Processed at": "Thời gian xử lý", "Not processed": "Chưa xử lý", Calendar: "Lịch", Today: "Hôm nay", Day: "Ngày", Week: "Tuần", Month: "Tháng", Schedule: "Lịch biểu", Create: "Tạo", "My calendars": "Lịch của tôi" },
  ja: { Contacts: "連絡先", Groups: "グループ", "Contact Details": "連絡先の詳細", "Group Information": "グループ情報", "Native Language": "母国語", "Global Members": "世界のメンバー", "Mute Notifications": "通知をミュート", Muted: "ミュート中", Off: "オフ", "Pin Conversation": "会話を固定", Pinned: "固定済み", No: "いいえ", Members: "メンバー", Member: "メンバー", "Leave Group": "グループを退出", "Block Contact": "連絡先をブロック", "My Profile": "マイプロフィール", Appearance: "外観", "Language & Settings": "言語と設定", "Log out": "ログアウト", "Last seen recently": "最近オンライン", Online: "オンライン", "New Conversation": "新しい会話", "Forward message": "メッセージを転送" },
  ko: { Contacts: "연락처", Groups: "그룹", "Contact Details": "연락처 세부정보", "Group Information": "그룹 정보", "Native Language": "모국어", "Global Members": "글로벌 멤버", "Mute Notifications": "알림 음소거", Muted: "음소거됨", Off: "꺼짐", "Pin Conversation": "대화 고정", Pinned: "고정됨", No: "아니요", Members: "멤버", Member: "멤버", "Leave Group": "그룹 나가기", "Block Contact": "연락처 차단", "My Profile": "내 프로필", Appearance: "화면 모드", "Language & Settings": "언어 및 설정", "Log out": "로그아웃", "Last seen recently": "최근 접속", Online: "온라인", "New Conversation": "새 대화", "Forward message": "메시지 전달" },
  zh: { Contacts: "联系人", Groups: "群组", "Contact Details": "联系人详情", "Group Information": "群组信息", "Native Language": "母语", "Global Members": "全球成员", "Mute Notifications": "静音通知", Muted: "已静音", Off: "关闭", "Pin Conversation": "置顶对话", Pinned: "已置顶", No: "否", Members: "成员", Member: "成员", "Leave Group": "退出群组", "Block Contact": "屏蔽联系人", "My Profile": "我的资料", Appearance: "外观", "Language & Settings": "语言和设置", "Log out": "退出登录", "Last seen recently": "最近上线", Online: "在线", "New Conversation": "新对话", "Forward message": "转发消息" },
  es: { Contacts: "Contactos", Groups: "Grupos", "Contact Details": "Detalles del contacto", "Group Information": "Información del grupo", "Native Language": "Idioma nativo", "Mute Notifications": "Silenciar notificaciones", Muted: "Silenciado", Off: "Desactivado", "Pin Conversation": "Fijar conversación", Pinned: "Fijada", No: "No", Members: "Miembros", Member: "Miembro", "Leave Group": "Salir del grupo", "Block Contact": "Bloquear contacto", "My Profile": "Mi perfil", Appearance: "Apariencia", "Language & Settings": "Idioma y configuración", "Log out": "Cerrar sesión", "Last seen recently": "Visto recientemente", Online: "En línea", "New Conversation": "Nueva conversación", "Forward message": "Reenviar mensaje" },
  fr: { Contacts: "Contacts", Groups: "Groupes", "Contact Details": "Détails du contact", "Group Information": "Informations du groupe", "My Profile": "Mon profil", Appearance: "Apparence", "Language & Settings": "Langue et paramètres", "Log out": "Se déconnecter", "Last seen recently": "Vu récemment", Online: "En ligne", "New Conversation": "Nouvelle discussion", "Forward message": "Transférer le message" },
  de: { Contacts: "Kontakte", Groups: "Gruppen", "Contact Details": "Kontaktdetails", "Group Information": "Gruppeninformationen", "My Profile": "Mein Profil", Appearance: "Darstellung", "Language & Settings": "Sprache und Einstellungen", "Log out": "Abmelden", "Last seen recently": "Kürzlich online", Online: "Online", "New Conversation": "Neue Unterhaltung", "Forward message": "Nachricht weiterleiten" },
  th: { Contacts: "รายชื่อติดต่อ", Groups: "กลุ่ม", "Contact Details": "รายละเอียดผู้ติดต่อ", "Group Information": "ข้อมูลกลุ่ม", "My Profile": "โปรไฟล์ของฉัน", Appearance: "รูปลักษณ์", "Language & Settings": "ภาษาและการตั้งค่า", "Log out": "ออกจากระบบ", "Last seen recently": "ออนไลน์ล่าสุด", Online: "ออนไลน์", "New Conversation": "การสนทนาใหม่", "Forward message": "ส่งต่อข้อความ" },
  id: { Contacts: "Kontak", Groups: "Grup", "Contact Details": "Detail kontak", "Group Information": "Informasi grup", "My Profile": "Profil saya", Appearance: "Tampilan", "Language & Settings": "Bahasa & Pengaturan", "Log out": "Keluar", "Last seen recently": "Terakhir dilihat baru-baru ini", Online: "Online", "New Conversation": "Percakapan baru", "Forward message": "Teruskan pesan" },
  pt: {}, ru: {}, ar: {}, hi: {},
};

// Complete every locale for every phrase the UI consumes. Keeping this separate
// from the seed catalog makes coverage auditable while older translations stay intact.
const phraseComplements: Record<Exclude<LanguageCode, 'en' | 'vi'>, Record<string, string>> = {
  ja: { Groups:"グループ", "multilingual members":"多言語メンバー", "Auto Live Translation Active":"自動リアルタイム翻訳が有効", "Create a New Group":"新しいグループを作成", "Suggested Contacts":"おすすめの連絡先", "No other conversation to forward to.":"転送先の会話がありません。", "Start a new chat":"新しいチャットを開始", "Logging out…":"ログアウト中…", Light:"ライト", Dark:"ダーク" },
  ko: { Groups:"그룹", "multilingual members":"다국어 멤버", "Auto Live Translation Active":"자동 실시간 번역 활성화", "Create a New Group":"새 그룹 만들기", "Suggested Contacts":"추천 연락처", "No other conversation to forward to.":"전달할 다른 대화가 없습니다.", "Start a new chat":"새 채팅 시작", "Logging out…":"로그아웃 중…", Light:"라이트", Dark:"다크" },
  zh: { Groups:"群组", "multilingual members":"多语言成员", "Auto Live Translation Active":"自动实时翻译已启用", "Create a New Group":"创建新群组", "Suggested Contacts":"推荐联系人", "No other conversation to forward to.":"没有其他可转发的对话。", "Start a new chat":"开始新聊天", "Logging out…":"正在退出…", Light:"浅色", Dark:"深色" },
  es: { Groups:"Grupos", "multilingual members":"miembros multilingües", "Auto Live Translation Active":"Traducción automática en vivo activa", "Global Members":"Miembros globales", "Create a New Group":"Crear un grupo nuevo", "Suggested Contacts":"Contactos sugeridos", "No other conversation to forward to.":"No hay otra conversación a la que reenviar.", "Start a new chat":"Iniciar un chat nuevo", "Logging out…":"Cerrando sesión…", Light:"Claro", Dark:"Oscuro" },
  fr: { Groups:"Groupes", "multilingual members":"membres multilingues", "Auto Live Translation Active":"Traduction automatique en direct activée", "Native Language":"Langue maternelle", "Global Members":"Membres internationaux", "Mute Notifications":"Désactiver les notifications", Muted:"En sourdine", Off:"Désactivé", "Pin Conversation":"Épingler la discussion", Pinned:"Épinglée", No:"Non", Members:"Membres", Member:"Membre", "Leave Group":"Quitter le groupe", "Block Contact":"Bloquer le contact", "Create a New Group":"Créer un groupe", "Suggested Contacts":"Contacts suggérés", "No other conversation to forward to.":"Aucune autre discussion disponible pour le transfert.", "Start a new chat":"Démarrer une discussion", "Logging out…":"Déconnexion…", Light:"Clair", Dark:"Sombre" },
  de: { Groups:"Gruppen", "multilingual members":"mehrsprachige Mitglieder", "Auto Live Translation Active":"Automatische Live-Übersetzung aktiv", "Native Language":"Muttersprache", "Global Members":"Internationale Mitglieder", "Mute Notifications":"Benachrichtigungen stummschalten", Muted:"Stumm", Off:"Aus", "Pin Conversation":"Unterhaltung anheften", Pinned:"Angeheftet", No:"Nein", Members:"Mitglieder", Member:"Mitglied", "Leave Group":"Gruppe verlassen", "Block Contact":"Kontakt blockieren", "Create a New Group":"Neue Gruppe erstellen", "Suggested Contacts":"Vorgeschlagene Kontakte", "No other conversation to forward to.":"Keine andere Unterhaltung zum Weiterleiten vorhanden.", "Start a new chat":"Neuen Chat starten", "Logging out…":"Abmeldung…", Light:"Hell", Dark:"Dunkel" },
  th: { Groups:"กลุ่ม", "multilingual members":"สมาชิกหลายภาษา", "Auto Live Translation Active":"เปิดใช้การแปลสดอัตโนมัติ", "Native Language":"ภาษาแม่", "Global Members":"สมาชิกทั่วโลก", "Mute Notifications":"ปิดเสียงการแจ้งเตือน", Muted:"ปิดเสียงแล้ว", Off:"ปิด", "Pin Conversation":"ปักหมุดการสนทนา", Pinned:"ปักหมุดแล้ว", No:"ไม่", Members:"สมาชิก", Member:"สมาชิก", "Leave Group":"ออกจากกลุ่ม", "Block Contact":"บล็อกผู้ติดต่อ", "Create a New Group":"สร้างกลุ่มใหม่", "Suggested Contacts":"ผู้ติดต่อที่แนะนำ", "No other conversation to forward to.":"ไม่มีการสนทนาอื่นให้ส่งต่อ", "Start a new chat":"เริ่มแชตใหม่", "Logging out…":"กำลังออกจากระบบ…", Light:"สว่าง", Dark:"มืด" },
  id: { Groups:"Grup", "multilingual members":"anggota multibahasa", "Auto Live Translation Active":"Terjemahan langsung otomatis aktif", "Native Language":"Bahasa ibu", "Global Members":"Anggota global", "Mute Notifications":"Bisukan notifikasi", Muted:"Dibisukan", Off:"Mati", "Pin Conversation":"Sematkan percakapan", Pinned:"Disematkan", No:"Tidak", Members:"Anggota", Member:"Anggota", "Leave Group":"Keluar dari grup", "Block Contact":"Blokir kontak", "Create a New Group":"Buat grup baru", "Suggested Contacts":"Kontak yang disarankan", "No other conversation to forward to.":"Tidak ada percakapan lain untuk diteruskan.", "Start a new chat":"Mulai chat baru", "Logging out…":"Sedang keluar…", Light:"Terang", Dark:"Gelap" },
  pt: { Contacts:"Contatos", Groups:"Grupos", "Search contacts...":"Pesquisar contatos...", "Search study groups...":"Pesquisar grupos...", "multilingual members":"membros multilíngues", "Auto Live Translation Active":"Tradução ao vivo ativada", "Contact Details":"Detalhes do contato", "Group Information":"Informações do grupo", "Native Language":"Idioma preferido", "Global Members":"Membros", "Mute Notifications":"Silenciar notificações", Muted:"Silenciado", Off:"Desativado", "Pin Conversation":"Fixar conversa", Pinned:"Fixada", No:"Não", Members:"Membros", Member:"Membro", "Leave Group":"Sair do grupo", "Block Contact":"Bloquear contato", "My Profile":"Meu perfil", Appearance:"Aparência", "Language & Settings":"Idioma e configurações", "Log out":"Sair", "Logging out…":"Saindo…", Light:"Claro", Dark:"Escuro", "Last seen recently":"Visto recentemente", Online:"Online", "New Conversation":"Nova conversa", "Create a New Group":"Criar grupo", "Suggested Contacts":"Contatos sugeridos", "Forward message":"Encaminhar mensagem", "No other conversation to forward to.":"Não há outra conversa para encaminhar.", "Start a new chat":"Iniciar conversa", "Your conversations live here":"Suas conversas ficam aqui", "Chat naturally across languages with AI-assisted instant translation and real-time smart suggestions.":"Converse entre idiomas com tradução instantânea e sugestões inteligentes em tempo real.", "Start a conversation":"Iniciar uma conversa" },
  ru: { Contacts:"Контакты", Groups:"Группы", "Search contacts...":"Поиск контактов...", "Search study groups...":"Поиск групп...", "multilingual members":"многоязычные участники", "Auto Live Translation Active":"Автоперевод включён", "Contact Details":"Сведения о контакте", "Group Information":"Информация о группе", "Native Language":"Предпочитаемый язык", "Global Members":"Участники", "Mute Notifications":"Отключить уведомления", Muted:"Без звука", Off:"Выкл.", "Pin Conversation":"Закрепить чат", Pinned:"Закреплено", No:"Нет", Members:"Участники", Member:"Участник", "Leave Group":"Выйти из группы", "Block Contact":"Заблокировать контакт", "My Profile":"Мой профиль", Appearance:"Оформление", "Language & Settings":"Язык и настройки", "Log out":"Выйти", "Logging out…":"Выход…", Light:"Светлая", Dark:"Тёмная", "Last seen recently":"Недавно в сети", Online:"В сети", "New Conversation":"Новый чат", "Create a New Group":"Создать группу", "Suggested Contacts":"Рекомендуемые контакты", "Forward message":"Переслать сообщение", "No other conversation to forward to.":"Нет другого чата для пересылки.", "Start a new chat":"Начать чат", "Your conversations live here":"Здесь будут ваши беседы", "Chat naturally across languages with AI-assisted instant translation and real-time smart suggestions.":"Общайтесь на разных языках с мгновенным переводом и умными подсказками.", "Start a conversation":"Начать беседу" },
  ar: { Contacts:"جهات الاتصال", Groups:"المجموعات", "Search contacts...":"ابحث في جهات الاتصال...", "Search study groups...":"ابحث في المجموعات...", "multilingual members":"أعضاء متعددو اللغات", "Auto Live Translation Active":"الترجمة المباشرة مفعّلة", "Contact Details":"تفاصيل جهة الاتصال", "Group Information":"معلومات المجموعة", "Native Language":"اللغة المفضلة", "Global Members":"الأعضاء", "Mute Notifications":"كتم الإشعارات", Muted:"مكتوم", Off:"إيقاف", "Pin Conversation":"تثبيت الدردشة", Pinned:"مثبّتة", No:"لا", Members:"الأعضاء", Member:"عضو", "Leave Group":"مغادرة المجموعة", "Block Contact":"حظر جهة الاتصال", "My Profile":"ملفي الشخصي", Appearance:"المظهر", "Language & Settings":"اللغة والإعدادات", "Log out":"تسجيل الخروج", "Logging out…":"جارٍ تسجيل الخروج…", Light:"فاتح", Dark:"داكن", "Last seen recently":"نشط مؤخراً", Online:"متصل", "New Conversation":"محادثة جديدة", "Create a New Group":"إنشاء مجموعة", "Suggested Contacts":"جهات اتصال مقترحة", "Forward message":"إعادة توجيه الرسالة", "No other conversation to forward to.":"لا توجد محادثة أخرى لإعادة التوجيه.", "Start a new chat":"بدء محادثة", "Your conversations live here":"محادثاتك هنا", "Chat naturally across languages with AI-assisted instant translation and real-time smart suggestions.":"تواصل عبر اللغات بترجمة فورية واقتراحات ذكية في الوقت الفعلي.", "Start a conversation":"بدء محادثة" },
  hi: { Contacts:"संपर्क", Groups:"समूह", "Search contacts...":"संपर्क खोजें...", "Search study groups...":"समूह खोजें...", "multilingual members":"बहुभाषी सदस्य", "Auto Live Translation Active":"लाइव अनुवाद चालू है", "Contact Details":"संपर्क विवरण", "Group Information":"समूह जानकारी", "Native Language":"पसंदीदा भाषा", "Global Members":"सदस्य", "Mute Notifications":"सूचनाएँ म्यूट करें", Muted:"म्यूट", Off:"बंद", "Pin Conversation":"चैट पिन करें", Pinned:"पिन किया गया", No:"नहीं", Members:"सदस्य", Member:"सदस्य", "Leave Group":"समूह छोड़ें", "Block Contact":"संपर्क ब्लॉक करें", "My Profile":"मेरी प्रोफ़ाइल", Appearance:"रूप", "Language & Settings":"भाषा और सेटिंग्स", "Log out":"लॉग आउट", "Logging out…":"लॉग आउट हो रहा है…", Light:"हल्का", Dark:"गहरा", "Last seen recently":"हाल ही में सक्रिय", Online:"ऑनलाइन", "New Conversation":"नई चैट", "Create a New Group":"समूह बनाएँ", "Suggested Contacts":"सुझाए गए संपर्क", "Forward message":"संदेश अग्रेषित करें", "No other conversation to forward to.":"अग्रेषित करने के लिए कोई अन्य चैट नहीं है।", "Start a new chat":"चैट शुरू करें", "Your conversations live here":"आपकी बातचीत यहाँ रहेगी", "Chat naturally across languages with AI-assisted instant translation and real-time smart suggestions.":"तुरंत अनुवाद और स्मार्ट सुझावों के साथ भाषाओं के पार सहजता से चैट करें।", "Start a conversation":"बातचीत शुरू करें" },
};
for (const language of Object.keys(phraseComplements) as Array<keyof typeof phraseComplements>) {
  Object.assign(phrases[language]!, phraseComplements[language]);
}

const requiredPhraseKeys = ["Contacts","Groups","multilingual members","Auto Live Translation Active","Contact Details","Group Information","Native Language","Global Members","Mute Notifications","Muted","Off","Pin Conversation","Pinned","No","Members","Member","Leave Group","Block Contact","My Profile","Appearance","Language & Settings","Log out","Logging out…","Light","Dark","Last seen recently","Online","New Conversation","Create a New Group","Suggested Contacts","Forward message","No other conversation to forward to.","Start a new chat"];
for (const language of ['ja','ko','zh','es','fr','de','th','id','pt','ru','ar','hi'] as LanguageCode[]) {
  const missing = requiredPhraseKeys.filter((key) => !phrases[language]?.[key]);
  if (missing.length) throw new Error(`Missing ${language} UI translations: ${missing.join(', ')}`);
}

export const tx = (language: LanguageCode, value: string) => phrases[language]?.[value] || value;
