import type { LanguageCode } from "../types";

const settingKeys = ["Preferred Language","Interface Language","Messages in other languages will automatically appear in your preferred language.","Controls, menus, and system messages use this language.","Automatic Translation","Translate foreign incoming messages instantly","Show Original by Default","Always show the untranslated text alongside translations","Translation Tone","natural","formal","friendly","Display Name","Bio","Save Profile Changes","Sound Notifications","Play audio chime on incoming messages","Read Receipts","Let contacts see when you read their messages","AI Smart Assistance","Enable quick rewrites, tone polish & auto grammar","Enable personal assistant","Show the assistant in your conversations"];
const settingValues: Record<LanguageCode, string[]> = {
  en: ["Translation language","App language","Messages will be translated into this language.","Menus and system messages will use this language.","Automatic translation","Automatically translate incoming messages","Show original messages","Show original text alongside translations","Translation style","Natural","Formal","Friendly","Display name","Bio","Save changes","Notification sounds","Play a sound for new messages","Read receipts","Let contacts know when you've read their messages","Personal assistant chatbot","Chat, translate, summarize, and improve your writing with your own assistant.","Enable personal assistant","Show the assistant in your conversations"],
  vi: ["Ngôn ngữ ưu tiên","Ngôn ngữ giao diện","Tin nhắn bằng ngôn ngữ khác sẽ tự động hiển thị bằng ngôn ngữ bạn chọn.","Nút điều khiển, menu và thông báo hệ thống dùng ngôn ngữ này.","Tự động dịch","Dịch ngay tin nhắn đến bằng ngôn ngữ khác","Luôn hiện bản gốc","Luôn hiện nội dung chưa dịch cùng bản dịch","Giọng điệu bản dịch","Tự nhiên","Trang trọng","Thân thiện","Tên hiển thị","Giới thiệu","Lưu thay đổi hồ sơ","Âm thanh thông báo","Phát âm thanh khi có tin nhắn đến","Xác nhận đã đọc","Cho phép liên hệ biết khi bạn đã đọc tin nhắn","Chatbot trợ lý cá nhân","Trò chuyện, dịch, tóm tắt và cải thiện nội dung với trợ lý riêng của bạn.","Bật trợ lý cá nhân","Hiển thị trợ lý trong các cuộc trò chuyện"],
  ja: ["優先言語","表示言語","他の言語のメッセージは優先言語で自動表示されます。","操作、メニュー、システムメッセージにこの言語を使用します。","自動翻訳","外国語の受信メッセージをすぐに翻訳","既定で原文を表示","翻訳と一緒に未翻訳の文章を常に表示","翻訳のトーン","自然","フォーマル","親しみやすい","表示名","自己紹介","プロフィールの変更を保存","通知音","受信メッセージの通知音を再生","既読通知","メッセージを読んだことを連絡先に表示","パーソナルアシスタントチャットボット","専用アシスタントと会話、翻訳、要約、文章改善ができます。","パーソナルアシスタントを有効化","会話にアシスタントを表示"],
  ko: ["선호 언어","인터페이스 언어","다른 언어의 메시지가 선호 언어로 자동 표시됩니다.","컨트롤, 메뉴 및 시스템 메시지에 이 언어를 사용합니다.","자동 번역","외국어 수신 메시지를 즉시 번역","기본적으로 원문 표시","번역과 함께 번역되지 않은 텍스트를 항상 표시","번역 어조","자연스럽게","격식 있게","친근하게","표시 이름","소개","프로필 변경 저장","알림 소리","메시지 수신 시 알림음 재생","읽음 확인","메시지를 읽었는지 연락처에 표시","개인 비서 챗봇","나만의 비서와 대화하고 번역, 요약 및 글쓰기를 개선하세요.","개인 비서 사용","대화에 비서 표시"],
  zh: ["首选语言","界面语言","其他语言的消息将自动以首选语言显示。","控件、菜单和系统消息使用此语言。","自动翻译","即时翻译收到的外语消息","默认显示原文","始终在译文旁显示未翻译文本","翻译语气","自然","正式","友好","显示名称","个人简介","保存资料更改","声音通知","收到消息时播放提示音","已读回执","让联系人知道你已阅读消息","个人助理聊天机器人","使用专属助理进行对话、翻译、总结和改进写作。","启用个人助理","在对话中显示助理"],
  es: ["Idioma preferido","Idioma de la interfaz","Los mensajes en otros idiomas aparecerán automáticamente en tu idioma preferido.","Los controles, menús y mensajes del sistema usan este idioma.","Traducción automática","Traducir al instante los mensajes recibidos en otros idiomas","Mostrar original de forma predeterminada","Mostrar siempre el texto sin traducir junto a las traducciones","Tono de traducción","Natural","Formal","Amable","Nombre para mostrar","Biografía","Guardar cambios del perfil","Notificaciones sonoras","Reproducir un sonido al recibir mensajes","Confirmaciones de lectura","Permitir que los contactos vean cuándo lees sus mensajes","Chatbot asistente personal","Conversa, traduce, resume y mejora tus textos con tu propio asistente.","Activar asistente personal","Mostrar el asistente en tus conversaciones"],
  fr: ["Langue préférée","Langue de l’interface","Les messages dans d’autres langues apparaîtront automatiquement dans votre langue préférée.","Les commandes, menus et messages système utilisent cette langue.","Traduction automatique","Traduire instantanément les messages reçus en langue étrangère","Afficher l’original par défaut","Toujours afficher le texte non traduit avec les traductions","Ton de traduction","Naturel","Formel","Amical","Nom d’affichage","Biographie","Enregistrer les modifications du profil","Notifications sonores","Émettre un son à la réception d’un message","Confirmations de lecture","Permettre aux contacts de voir quand vous lisez leurs messages","Chatbot assistant personnel","Discutez, traduisez, résumez et améliorez vos textes avec votre propre assistant.","Activer l’assistant personnel","Afficher l’assistant dans vos conversations"],
  de: ["Bevorzugte Sprache","Oberflächensprache","Nachrichten in anderen Sprachen werden automatisch in der bevorzugten Sprache angezeigt.","Bedienelemente, Menüs und Systemmeldungen verwenden diese Sprache.","Automatische Übersetzung","Eingehende fremdsprachige Nachrichten sofort übersetzen","Original standardmäßig anzeigen","Unübersetzten Text immer neben der Übersetzung anzeigen","Übersetzungsstil","Natürlich","Formell","Freundlich","Anzeigename","Biografie","Profiländerungen speichern","Tonbenachrichtigungen","Bei eingehenden Nachrichten einen Ton abspielen","Lesebestätigungen","Kontakte sehen lassen, wann Nachrichten gelesen wurden","Persönlicher Assistent-Chatbot","Chatten, übersetzen, zusammenfassen und Texte mit Ihrem eigenen Assistenten verbessern.","Persönlichen Assistenten aktivieren","Assistenten in Unterhaltungen anzeigen"],
  th: ["ภาษาที่ต้องการ","ภาษาอินเทอร์เฟซ","ข้อความภาษาอื่นจะแสดงเป็นภาษาที่คุณเลือกโดยอัตโนมัติ","ส่วนควบคุม เมนู และข้อความระบบใช้ภาษานี้","การแปลอัตโนมัติ","แปลข้อความภาษาต่างประเทศที่ได้รับทันที","แสดงต้นฉบับเป็นค่าเริ่มต้น","แสดงข้อความที่ยังไม่ได้แปลพร้อมคำแปลเสมอ","โทนการแปล","เป็นธรรมชาติ","เป็นทางการ","เป็นมิตร","ชื่อที่แสดง","ประวัติย่อ","บันทึกการเปลี่ยนแปลงโปรไฟล์","เสียงแจ้งเตือน","เล่นเสียงเมื่อมีข้อความเข้า","ใบตอบรับการอ่าน","ให้ผู้ติดต่อเห็นเมื่อคุณอ่านข้อความ","แชตบอตผู้ช่วยส่วนตัว","สนทนา แปล สรุป และปรับปรุงงานเขียนด้วยผู้ช่วยส่วนตัวของคุณ","เปิดใช้ผู้ช่วยส่วนตัว","แสดงผู้ช่วยในการสนทนา"],
  id: ["Bahasa pilihan","Bahasa antarmuka","Pesan dalam bahasa lain akan otomatis tampil dalam bahasa pilihan Anda.","Kontrol, menu, dan pesan sistem menggunakan bahasa ini.","Terjemahan otomatis","Terjemahkan pesan masuk berbahasa asing secara langsung","Tampilkan teks asli secara default","Selalu tampilkan teks yang belum diterjemahkan bersama terjemahan","Nada terjemahan","Alami","Formal","Ramah","Nama tampilan","Bio","Simpan perubahan profil","Notifikasi suara","Putar bunyi saat pesan masuk","Tanda dibaca","Izinkan kontak melihat saat Anda membaca pesan","Chatbot asisten pribadi","Mengobrol, menerjemahkan, merangkum, dan menyempurnakan tulisan dengan asisten pribadi Anda.","Aktifkan asisten pribadi","Tampilkan asisten dalam percakapan"],
  pt: ["Idioma preferido","Idioma da interface","As mensagens em outros idiomas aparecerão automaticamente no seu idioma preferido.","Os controles, menus e mensagens do sistema usam este idioma.","Tradução automática","Traduzir instantaneamente mensagens recebidas em outros idiomas","Mostrar original por padrão","Sempre mostrar o texto não traduzido junto às traduções","Tom da tradução","Natural","Formal","Amigável","Nome de exibição","Biografia","Salvar alterações do perfil","Sons de notificação","Reproduzir som ao receber mensagens","Confirmações de leitura","Permitir que contatos vejam quando você leu mensagens","Chatbot de assistente pessoal","Converse, traduza, resuma e melhore sua escrita com seu assistente.","Ativar assistente pessoal","Mostrar o assistente nas conversas"],
  ru: ["Предпочитаемый язык","Язык интерфейса","Сообщения на других языках будут автоматически отображаться на предпочитаемом языке.","Элементы управления, меню и системные сообщения используют этот язык.","Автоперевод","Мгновенно переводить входящие сообщения на другом языке","Показывать оригинал по умолчанию","Всегда показывать оригинальный текст рядом с переводом","Стиль перевода","Естественный","Формальный","Дружелюбный","Отображаемое имя","О себе","Сохранить изменения профиля","Звуковые уведомления","Воспроизводить звук при новом сообщении","Отчёты о прочтении","Разрешить контактам видеть, когда вы прочитали сообщения","Чат-бот персонального помощника","Общайтесь, переводите, резюмируйте и улучшайте текст с личным помощником.","Включить персонального помощника","Показывать помощника в беседах"],
  ar: ["اللغة المفضلة","لغة الواجهة","ستظهر الرسائل باللغات الأخرى تلقائياً بلغتك المفضلة.","تستخدم عناصر التحكم والقوائم ورسائل النظام هذه اللغة.","الترجمة التلقائية","ترجمة الرسائل الواردة بلغات أخرى فوراً","إظهار النص الأصلي افتراضياً","إظهار النص غير المترجم بجانب الترجمة دائماً","نبرة الترجمة","طبيعي","رسمي","ودود","اسم العرض","نبذة","حفظ تغييرات الملف الشخصي","أصوات الإشعارات","تشغيل صوت عند وصول رسالة","إيصالات القراءة","السماح لجهات الاتصال بمعرفة وقت قراءة الرسائل","روبوت المساعد الشخصي","تحدث وترجم ولخّص وحسّن كتابتك مع مساعدك الشخصي.","تفعيل المساعد الشخصي","إظهار المساعد في محادثاتك"],
  hi: ["पसंदीदा भाषा","इंटरफ़ेस भाषा","अन्य भाषाओं के संदेश आपकी पसंदीदा भाषा में अपने-आप दिखेंगे।","नियंत्रण, मेनू और सिस्टम संदेश इस भाषा का उपयोग करेंगे।","स्वचालित अनुवाद","अन्य भाषाओं के आने वाले संदेशों का तुरंत अनुवाद करें","डिफ़ॉल्ट रूप से मूल दिखाएँ","अनुवाद के साथ मूल पाठ हमेशा दिखाएँ","अनुवाद का लहजा","स्वाभाविक","औपचारिक","मैत्रीपूर्ण","प्रदर्शित नाम","परिचय","प्रोफ़ाइल बदलाव सहेजें","सूचना ध्वनियाँ","नया संदेश आने पर ध्वनि चलाएँ","पढ़े जाने की रसीदें","संपर्कों को बताएँ कि आपने संदेश कब पढ़े","निजी सहायक चैटबॉट","अपने सहायक के साथ चैट करें, अनुवाद करें, सारांश बनाएँ और लेखन सुधारें।","निजी सहायक सक्षम करें","बातचीत में सहायक दिखाएँ"],
};
export const settingText = (language: LanguageCode, value: string) => {
  const index = settingKeys.indexOf(value);
  return index < 0 ? value : settingValues[language][index];
};
